Name = "Webnames"
Description = ''''''
URL = "https://www.webnames.ru/"
Code = "webnames"
Since = "v4.14.2"

Example = '''
WEBNAMES_API_KEY=xxxxxx \
lego --email you@example.com --dns webnames --domains my.example.org run
'''

Additional = '''
## API key 

Для получения ключа необходимо сменить DNS-сервера на *.nameself.com: Личный кабинет / Мои домены и услуги / Выбрать необходимый домен / DNS-серверы

Ключ API можно будет найти: Личный кабинет / Мои домены и услуги / Выбрать необходимый домен / Управление зоной / Настройка acme.sh или certbot
'''

[Configuration]
[Configuration.Credentials]
WEBNAMES_API_KEY = "Domain api key"
[Configuration.Additional]
WEBNAMES_POLLING_INTERVAL = "Time between DNS propagation check"
WEBNAMES_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
WEBNAMES_TTL = "The TTL of the TXT record used for the DNS challenge"
WEBNAMES_HTTP_TIMEOUT = "API request timeout"
WEBNAMES_SEQUENCE_INTERVAL = "Time between sequential requests"

[Links]
API = "https://www.webnames.ru/scripts/json_domain_zone_manager.pl"
